import '@main/handlers/general.handler'
import '@main/handlers/store.handler'
import '@main/handlers/notepads.handler'
import '@main/handlers/pages.handler'
import '@main/handlers/notes.handler'
import '@main/handlers/updater.handler'
import '@main/handlers/initials.handler'