name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup LLVM
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: 17
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.x'
    - name: install apt requirements
      run: sudo apt install -y gcc-multilib
    - name: install python dependencies
      run: python -m pip install --upgrade setuptools
    - name: upgrade node-gyp
      run: npm install -g node-gyp@latest
    - name: install dependencies
      run: yarn install
    - name: build current system distributables
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn nps publish.linux

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.x'
    - name: install rosetta
      run: softwareupdate --install-rosetta --agree-to-license
    - name: install python dependencies
      run: python -m pip install --upgrade setuptools
    - name: upgrade node-gyp
      run: npm install -g node-gyp@latest
    - name: install dependencies
      run: yarn install
    - name: build current system distributables
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn nps publish.darwin

  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.x'
    - name: install python dependencies
      run: python -m pip install --upgrade setuptools
    - name: upgrade node-gyp
      run: npm install -g node-gyp@latest
    - name: install dependencies
      run: yarn install
    - name: build current system distributables
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn nps publish.win32