name: Test
on:
  push:
    branches:
      - staging

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 17
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.x'
      - name: install python dependencies
        run: python -m pip install --upgrade setuptools
      - name: install dependencies
        run: npm install

      - name: run tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run nps test
      - name: Check there is no problem packaging the app
        run: npm run nps build.linux

  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.x'
      - name: install rosetta
        run: softwareupdate --install-rosetta --agree-to-license
      - name: install python dependencies
        run: python -m pip install --upgrade setuptools
      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run nps test
      - name: Check there is no problem packaging the app
        run: npm run nps build.darwin

  publish_on_win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.x'
      - name: install python dependencies
        run: python -m pip install --upgrade setuptools
      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run nps test
      - name: Check there is no problem packaging the app
        run: npm run nps build.win32