name: Test
on: [pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.x'
    - name: install python dependencies
      run: python -m pip install --upgrade setuptools
    - name: upgrade node-gyp
      run: npm install -g node-gyp@latest
    - name: install dependencies
      run: npm install
    - name: run tests
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run nps test

  build_on_mac:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.x'
    - name: install python dependencies
      run: python -m pip install --upgrade setuptools
    - name: upgrade node-gyp
      run: npm install -g node-gyp@latest
    - name: install node dependencies
      run: npm install
    - name: run tests
      run: npm run nps test

  build_on_win:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.x'
    - name: install python dependencies
      run: python -m pip install --upgrade setuptools
    - name: upgrade node-gyp
      run: npm install -g node-gyp@latest
    - name: install dependencies
      run: npm install
    - name: run tests
      run: npm run nps test